language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache
php:
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly
matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly
    fast_finish: true
before_script:
    - composer self-update
install:
    - composer install
script:
    - vendor/bin/phpunit
    - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover; fi
after_script:
    - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
